### ISSUE TITLE
Unexpected error.

### ISSUE THREAD

**Issue by frabrunelle** [nicolaslopezj/orion-exporter#3]
When I use the latest version of with orion-exporter and I click "Export", there is another tab that opens saying "Unexpected error." instead of correctly exporting all of my Orion collections.

It was working before so I assume it must be due to a recent change.

Are you able to reproduce this issue?

Thank you, this package is super useful and yet another plus for using Orion :smile:

**Comment by frabrunelle** [comment]
I just noticed that there is the following error in my terminal:

```
W20150820-11:11:24.903(-4)? (STDERR)
W20150820-11:11:24.904(-4)? (STDERR) /Users/frabrunelle/.meteor/packages/meteor-tool/.1.1.4.15xphj0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150820-11:11:24.904(-4)? (STDERR)                        throw(ex);
W20150820-11:11:24.904(-4)? (STDERR)                              ^
W20150820-11:11:24.904(-4)? (STDERR) ReferenceError: collections is not defined
W20150820-11:11:24.904(-4)? (STDERR)     at packages/nicolaslopezj:orion-exporter/exporter_server.js:18:1
W20150820-11:11:24.904(-4)? (STDERR)     at doCall (packages/meteorhacks:picker/lib/implementation.js:98:1)
W20150820-11:11:24.904(-4)? (STDERR)     at [object Object].PickerImp._processRoute (packages/meteorhacks:picker/lib/implementation.js:92:1)
W20150820-11:11:24.904(-4)? (STDERR)     at processNextRoute (packages/meteorhacks:picker/lib/implementation.js:60:1)
W20150820-11:11:24.904(-4)? (STDERR)     at processNextMiddleware (packages/meteorhacks:picker/lib/implementation.js:48:1)
W20150820-11:11:24.904(-4)? (STDERR)     at jsonParser (/Users/frabrunelle/.meteor/packages/nicolaslopezj_orion-exporter/.1.1.1.9mi6zv++os+web.browser+web.cordova/npm/node_modules/body-parser/lib/types/json.js:100:40)
W20150820-11:11:24.904(-4)? (STDERR)     at doCall (packages/meteorhacks:picker/lib/implementation.js:110:1)
=> Exited with code: 8
```

**Comment by romans127** [comment]
+1 I'm having the same issue.

**Comment by romans127** [comment]
Found the issue. In `exporter_server.js` , it looks like orion.collections.list needs to be the value for collections. so simply update right before you loop through collections `collections = orion.collections.list` and the export will work properly.
