### ISSUE TITLE
Error : Export throws error when using pages.

### ISSUE THREAD

**Issue by romans127** [nicolaslopezj/orion-exporter#4]
The following error is thrown when trying to render an export with the pages package installed. 

``` sh
W20150828-19:03:56.739(-7)? (STDERR) 
W20150828-19:03:56.747(-7)? (STDERR) C:\Users\rwatts\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20150828-19:03:56.748(-7)? (STDERR)                                            throw(ex);
W20150828-19:03:56.748(-7)? (STDERR)                                                  ^
W20150828-19:03:56.748(-7)? (STDERR) ReferenceError: pages is not defined
W20150828-19:03:56.748(-7)? (STDERR)     at packages/nicolaslopezj:orion-exporter/exporter_server.js:14:1
W20150828-19:03:56.748(-7)? (STDERR)     at doCall (packages/meteorhacks:picker/lib/implementation.js:98:1)
W20150828-19:03:56.749(-7)? (STDERR)     at [object Object].PickerImp._processRoute (packages/meteorhacks:picker/lib/implementation.js:92:1)
W20150828-19:03:56.749(-7)? (STDERR)     at processNextRoute (packages/meteorhacks:picker/lib/implementation.js:60:1)
W20150828-19:03:56.749(-7)? (STDERR)     at processNextMiddleware (packages/meteorhacks:picker/lib/implementation.js:48:1)
W20150828-19:03:56.749(-7)? (STDERR)     at jsonParser (C:\Users\rwatts\AppData\Local\.meteor\packages\nicolaslopezj_orion-exporter\1.1.3\npm\node_modules\body-parser\lib\types\json.js:100:40)
W20150828-19:03:56.749(-7)? (STDERR)     at doCall (packages/meteorhacks:picker/lib/implementation.js:110:1)

```

**Comment by nicolaslopezj** [comment]
I think this is already fixed

**Comment by romans127** [comment]
Export when app is on Digital Ocean throws an error. I believe it may be nginx related. 
Any idea of what the fix could be ? 
http://screencast.com/t/xv3g2L1HYpG

**Comment by nicolaslopezj** [comment]
I don't know. You could check the nginx logs
